# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
    # You can also specify other tool versions:
    rust: "1.70"
  jobs:
    post_create_environment:
      - pip install sphinx-rtd-theme
    pre_build:
      - sphinx-apidoc -o doc/source pysui/

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: doc/source/conf.py

# Data class documentation
python:
  install:
    - requirements: requirements.txt
