#    Copyright Frank V. Castellucci
#    SPDX-License-Identifier: Apache-2.0

# -*- coding: utf-8 -*-

# Generated by: python samples/mtobcs.py -m samples/mtobcs_sysstate.json -o con
# Source package: 0x3 (sui-system, Sui framework)
# Targets: SuiSystemStateInnerV2, ValidatorSet, Validator
# Do not hand-edit — regenerate via mtobcs.py if the on-chain types change.

"""BCS types for Sui system state, validator set, and validator deserialization."""

from typing import Any
import json
import pysui.sui.sui_bcs.bcs_stnd as bcse
import pysui.sui.sui_bcs.pysui_bcs as pbcsbase


class Url(pbcsbase.BCS_Struct):
    """Generated from 0x0000000000000000000000000000000000000000000000000000000000000002::url::Url"""

    _fields = [("url", bcse.String)]


class VecSet_Address(pbcsbase.BCS_Struct):
    """Generated from 0x0000000000000000000000000000000000000000000000000000000000000002::vec_set::VecSet"""

    _fields = [("contents", [bcse.Address, None, True])]


class Entry_Address_U64(pbcsbase.BCS_Struct):
    """Generated from 0x0000000000000000000000000000000000000000000000000000000000000002::vec_map::Entry"""

    _fields = [("key", bcse.Address), ("value", bcse.U64)]


class StakingPool_optional_activation_epoch(pbcsbase.BCS_Optional):
    _type = bcse.U64

    def to_json(self, sort_keys=False, indent=4):
        """Serialize the optional value to a JSON string."""
        amap = self.to_json_serializable()
        return json.dumps(amap, sort_keys=sort_keys, indent=indent)


class StakingPool_optional_deactivation_epoch(pbcsbase.BCS_Optional):
    _type = bcse.U64

    def to_json(self, sort_keys=False, indent=4):
        """Serialize the optional value to a JSON string."""
        amap = self.to_json_serializable()
        return json.dumps(amap, sort_keys=sort_keys, indent=indent)


class StakingPool(pbcsbase.BCS_Struct):
    """Generated from 0x0000000000000000000000000000000000000000000000000000000000000003::staking_pool::StakingPool"""

    _fields = [
        ("id", bcse.Address),
        ("activation_epoch", StakingPool_optional_activation_epoch),
        ("deactivation_epoch", StakingPool_optional_deactivation_epoch),
        ("sui_balance", bcse.U64),
        ("rewards_pool", bcse.Balance),
        ("pool_token_balance", bcse.U64),
        ("exchange_rates", bcse.Table),
        ("pending_stake", bcse.U64),
        ("pending_total_sui_withdraw", bcse.U64),
        ("pending_pool_token_withdraw", bcse.U64),
        ("extra_fields", bcse.Bag),
    ]


class ID(pbcsbase.BCS_Struct):
    """Generated from 0x0000000000000000000000000000000000000000000000000000000000000002::object::ID"""

    _fields = [("bytes", bcse.Address)]


class ValidatorMetadata_optional_next_epoch_protocol_pubkey_bytes(pbcsbase.BCS_Optional):
    _type = [bcse.U8, None, True]

    def to_json(self, sort_keys=False, indent=4):
        """Serialize the optional value to a JSON string."""
        amap = self.to_json_serializable()
        return json.dumps(amap, sort_keys=sort_keys, indent=indent)


class ValidatorMetadata_optional_next_epoch_proof_of_possession(pbcsbase.BCS_Optional):
    _type = [bcse.U8, None, True]

    def to_json(self, sort_keys=False, indent=4):
        """Serialize the optional value to a JSON string."""
        amap = self.to_json_serializable()
        return json.dumps(amap, sort_keys=sort_keys, indent=indent)


class ValidatorMetadata_optional_next_epoch_network_pubkey_bytes(pbcsbase.BCS_Optional):
    _type = [bcse.U8, None, True]

    def to_json(self, sort_keys=False, indent=4):
        """Serialize the optional value to a JSON string."""
        amap = self.to_json_serializable()
        return json.dumps(amap, sort_keys=sort_keys, indent=indent)


class ValidatorMetadata_optional_next_epoch_worker_pubkey_bytes(pbcsbase.BCS_Optional):
    _type = [bcse.U8, None, True]

    def to_json(self, sort_keys=False, indent=4):
        """Serialize the optional value to a JSON string."""
        amap = self.to_json_serializable()
        return json.dumps(amap, sort_keys=sort_keys, indent=indent)


class ValidatorMetadata_optional_next_epoch_net_address(pbcsbase.BCS_Optional):
    _type = bcse.String

    def to_json(self, sort_keys=False, indent=4):
        """Serialize the optional value to a JSON string."""
        amap = self.to_json_serializable()
        return json.dumps(amap, sort_keys=sort_keys, indent=indent)


class ValidatorMetadata_optional_next_epoch_p2p_address(pbcsbase.BCS_Optional):
    _type = bcse.String

    def to_json(self, sort_keys=False, indent=4):
        """Serialize the optional value to a JSON string."""
        amap = self.to_json_serializable()
        return json.dumps(amap, sort_keys=sort_keys, indent=indent)


class ValidatorMetadata_optional_next_epoch_primary_address(pbcsbase.BCS_Optional):
    _type = bcse.String

    def to_json(self, sort_keys=False, indent=4):
        """Serialize the optional value to a JSON string."""
        amap = self.to_json_serializable()
        return json.dumps(amap, sort_keys=sort_keys, indent=indent)


class ValidatorMetadata_optional_next_epoch_worker_address(pbcsbase.BCS_Optional):
    _type = bcse.String

    def to_json(self, sort_keys=False, indent=4):
        """Serialize the optional value to a JSON string."""
        amap = self.to_json_serializable()
        return json.dumps(amap, sort_keys=sort_keys, indent=indent)


class ValidatorMetadata(pbcsbase.BCS_Struct):
    """Generated from 0x0000000000000000000000000000000000000000000000000000000000000003::validator::ValidatorMetadata"""

    _fields = [
        ("sui_address", bcse.Address),
        ("protocol_pubkey_bytes", [bcse.U8, None, True]),
        ("network_pubkey_bytes", [bcse.U8, None, True]),
        ("worker_pubkey_bytes", [bcse.U8, None, True]),
        ("proof_of_possession", [bcse.U8, None, True]),
        ("name", bcse.String),
        ("description", bcse.String),
        ("image_url", Url),
        ("project_url", Url),
        ("net_address", bcse.String),
        ("p2p_address", bcse.String),
        ("primary_address", bcse.String),
        ("worker_address", bcse.String),
        ("next_epoch_protocol_pubkey_bytes", ValidatorMetadata_optional_next_epoch_protocol_pubkey_bytes),
        ("next_epoch_proof_of_possession", ValidatorMetadata_optional_next_epoch_proof_of_possession),
        ("next_epoch_network_pubkey_bytes", ValidatorMetadata_optional_next_epoch_network_pubkey_bytes),
        ("next_epoch_worker_pubkey_bytes", ValidatorMetadata_optional_next_epoch_worker_pubkey_bytes),
        ("next_epoch_net_address", ValidatorMetadata_optional_next_epoch_net_address),
        ("next_epoch_p2p_address", ValidatorMetadata_optional_next_epoch_p2p_address),
        ("next_epoch_primary_address", ValidatorMetadata_optional_next_epoch_primary_address),
        ("next_epoch_worker_address", ValidatorMetadata_optional_next_epoch_worker_address),
        ("extra_fields", bcse.Bag),
    ]


class Entry_Address_VecSet(pbcsbase.BCS_Struct):
    """Generated from 0x0000000000000000000000000000000000000000000000000000000000000002::vec_map::Entry"""

    _fields = [("key", bcse.Address), ("value", VecSet_Address)]


class VecMap_Address_U64(pbcsbase.BCS_Struct):
    """Generated from 0x0000000000000000000000000000000000000000000000000000000000000002::vec_map::VecMap"""

    _fields = [("contents", [Entry_Address_U64, None, True])]


class Validator(pbcsbase.BCS_Struct):
    """Generated from 0x0000000000000000000000000000000000000000000000000000000000000003::validator::Validator"""

    _fields = [
        ("metadata", ValidatorMetadata),
        ("voting_power", bcse.U64),
        ("operation_cap_id", ID),
        ("gas_price", bcse.U64),
        ("staking_pool", StakingPool),
        ("commission_rate", bcse.U64),
        ("next_epoch_stake", bcse.U64),
        ("next_epoch_gas_price", bcse.U64),
        ("next_epoch_commission_rate", bcse.U64),
        ("extra_fields", bcse.Bag),
    ]


class StakeSubsidy(pbcsbase.BCS_Struct):
    """Generated from 0x0000000000000000000000000000000000000000000000000000000000000003::stake_subsidy::StakeSubsidy"""

    _fields = [
        ("balance", bcse.Balance),
        ("distribution_counter", bcse.U64),
        ("current_distribution_amount", bcse.U64),
        ("stake_subsidy_period_length", bcse.U64),
        ("stake_subsidy_decrease_rate", bcse.U16),
        ("extra_fields", bcse.Bag),
    ]


class VecMap_Address_VecSet(pbcsbase.BCS_Struct):
    """Generated from 0x0000000000000000000000000000000000000000000000000000000000000002::vec_map::VecMap"""

    _fields = [("contents", [Entry_Address_VecSet, None, True])]


class SystemParametersV2(pbcsbase.BCS_Struct):
    """Generated from 0x0000000000000000000000000000000000000000000000000000000000000003::sui_system_state_inner::SystemParametersV2"""

    _fields = [
        ("epoch_duration_ms", bcse.U64),
        ("stake_subsidy_start_epoch", bcse.U64),
        ("min_validator_count", bcse.U64),
        ("max_validator_count", bcse.U64),
        ("min_validator_joining_stake", bcse.U64),
        ("validator_low_stake_threshold", bcse.U64),
        ("validator_very_low_stake_threshold", bcse.U64),
        ("validator_low_stake_grace_period", bcse.U64),
        ("extra_fields", bcse.Bag),
    ]


class StorageFund(pbcsbase.BCS_Struct):
    """Generated from 0x0000000000000000000000000000000000000000000000000000000000000003::storage_fund::StorageFund"""

    _fields = [
        ("total_object_storage_rebates", bcse.Balance),
        ("non_refundable_balance", bcse.Balance),
    ]


class ValidatorSet(pbcsbase.BCS_Struct):
    """Generated from 0x0000000000000000000000000000000000000000000000000000000000000003::validator_set::ValidatorSet"""

    _fields = [
        ("total_stake", bcse.U64),
        ("active_validators", [Validator, None, True]),
        ("pending_active_validators", bcse.TableVec),
        ("pending_removals", [bcse.U64, None, True]),
        ("staking_pool_mappings", bcse.Table),
        ("inactive_validators", bcse.Table),
        ("validator_candidates", bcse.Table),
        ("at_risk_validators", VecMap_Address_U64),
        ("extra_fields", bcse.Bag),
    ]


class SuiSystemStateInnerV2(pbcsbase.BCS_Struct):
    """Generated from 0x3::sui_system_state_inner::SuiSystemStateInnerV2"""

    _fields = [
        ("epoch", bcse.U64),
        ("protocol_version", bcse.U64),
        ("system_state_version", bcse.U64),
        ("validators", ValidatorSet),
        ("storage_fund", StorageFund),
        ("parameters", SystemParametersV2),
        ("reference_gas_price", bcse.U64),
        ("validator_report_records", VecMap_Address_VecSet),
        ("stake_subsidy", StakeSubsidy),
        ("safe_mode", bool),
        ("safe_mode_storage_rewards", bcse.Balance),
        ("safe_mode_computation_rewards", bcse.Balance),
        ("safe_mode_storage_rebates", bcse.U64),
        ("safe_mode_non_refundable_storage_fee", bcse.U64),
        ("epoch_start_timestamp_ms", bcse.U64),
        ("extra_fields", bcse.Bag),
    ]
